FROM itau-ey5-docker.depdes.artifactory.prod.cloud.ihf/orangestack-grpcgateway:latest as build
ADD src/main/proto/ /proto
RUN /config/gateway.sh

FROM alpine:latest
RUN apk --update --no-cache add ca-certificates

WORKDIR /gateway/
COPY --from=build /output/ .
EXPOSE 8081
ENTRYPOINT ["./gateway"]